Enhancement: attributes can have settings + added limit price settings to configure limit appearance
buchen/portfolio pull request #2443
Opened 2021-09-30 19:51 UTC by OnkelDok

### Dieser Pull Request bezieht sich auf folgende Anfragen:
- [Farben einstellbar für Überschreiten/Unterschreiten der Limits](https://forum.portfolio-performance.info/t/limits-min-max-in-wertpapieruebersicht/557/7?u)
- [Abstand zwischen Preis und Limit anzeigen (absolut/relativ)](https://forum.portfolio-performance.info/t/prozentualer-absoluter-abstand-zum-limit-darstellen/8366)

### Mit dem aktuellen Stand des Pull Request würde folgendes neu sein:
* Attribute können nun Einstellungen haben (wäre mMn eine Voraussetzung für #446)
* Limit-Preis-Attribut hat neue Einstellung erhalten
* Limit-Preis-Spalte nutzt neue Einstellungen. So würde es aussehen wenn die Einstellungen geändert werden:
![grafik](https://user-images.githubusercontent.com/90478568/135452089-0bbfacfa-87c7-4161-9ee2-10e9d6771bdf.png)
Außerdem kann die Farbe bei über-/unterschreiten von Limits angepasst werden
* Nach dem Laden der XML wird den Limit-Preis-Attributen das default-Setting zugewiesen (**ohne Änderung der Einstellung sieht erstmal alles so aus wie bisher**)

### Offene Punkt sind noch:

* View zum Ändern der Attributseinstellungen. Hier sind mir zwei Möglichkeiten eingefallen wie man die Attributseinstellungen dem Benutzer anzeigt:
  * **A)** In den Attributseinstellungen auf der rechten Seite einen festen Platz reservieren und Einstellungen anzeigen sobald man ein Attribut in der Liste markiert. Nachteilig ist hierbei, dass der Platz verbraucht wird auch wenn ein Attribut keine Einstellungen hat - und das sind aktuell ja alle.
  * **B)** In den Attributseinstellungen eine extra Spalte anzeigen. Wenn ein Attribut Einstellungen hat, dann wird in dieser Spalte ein Button sichtbar. Klickt man darauf öffnet sich ein Dialog in dem die Attributs-Einstellungen sicht- & änderbar sind. Finde ich die schönere Lösung.

**Gibt es noch weitere Möglichkeiten? Welche ist geeignet um Attributseinstellungen anzuzeigen?**

### Zusätzlich noch eine Frage:
Ich hatte mir eine View für die LimitPriceSettings gebastelt (ist aber bisher nicht im branch commited). Dort wollte ich auch die Farben einstellbar machen. Die aktuell eingestellte wollte ich als Hintergrundfarbe eines Labels setzen um direkt zu sehen welche Farbe eingestellt ist.
Egal welche Farbe ich zugewiesen habe (selbst hart zugewiesen wie im code snippet unten), das Label behielt seine dunkle Farbe. Woran liegt das?

```java
Label colorLabel = new Label(colorContainer, SWT.CENTER| SWT.BORDER);             
colorLabel.setBackground(Colors.RED);
```

![grafik](https://user-images.githubusercontent.com/90478568/135517944-9d259593-39f2-4374-b5a7-529e790eca7f.png)

2021-09-30 21:56 UTC, OnkelDok commented
Ich sehe gerade die Unittests die FAIL gehen. Die haben alle damit zu tun, dass die Version der Settings (https://github.com/buchen/portfolio/pull/2443/commits/8f20b03d98294850bd9cefdde10652eda8506ce9#diff-abe10f679796db38afda8c5d595ccd354bb8c70c8b0aa238b7d7c9cbfa63d53b) und die Struktur sich geändert hat (https://github.com/buchen/portfolio/commit/8f20b03d98294850bd9cefdde10652eda8506ce9#diff-d03a2e8e03a8afdd714a1a30bda3eff0724e3c24346ab7bfbe7ccb846ba705fc). Muss ich mir später nochmal genauer ansehen. Da steig ich auf die Schnelle noch nicht durch was beim Laden der verschiedenen Datei-Arten anders gemacht wird.

Oder müssen einfach die Quelldateien für den Unittest angepasst werden?

2021-10-01 19:37 UTC, OnkelDok commented
> Egal welche Farbe ich zugewiesen habe (selbst hart zugewiesen wie im code snippet unten), das Label behielt seine dunkle Farbe. Woran liegt das?

Das liegt ja vermutlich daran, dass ein Theme die Farbe festlegt, richtig?
Ich hab dazu nun das ColoredLabel gefunden, mit welchem die Farbanzeige nun möglich ist:
![grafik](https://user-images.githubusercontent.com/90478568/135676231-1f77b25b-fef3-4b8b-828e-235980e68ca7.png)

Damit sehe ich aktuell zwei Punkte offen:
* **Unittests müssen wieder PASS gehen:** Hier überlege ich ob man die Attribute-Settings des LimitPrice einfach erstmal null lässt solange der Nutzer nicht aktiv in die Einstellungen geht. In der Logik wird dann entsprechend mit den default-Settings gearbeitet. Sobald er die Einstellungen anzeigt, wird dann auch das settings-Feld mit den settings gesetzt. Damit fällt das Anpassen der PP-Einstellungen beim Laden der Einstellungedatei (und damit auch die neue Settings-Version)
* **Wo ist Settings-View der Attributs-Einstellungen am besten darzustellen?:** Hier bin ich noch nicht weiter gekommen. Ich werde mal schauen ob in der Tabelle eine neue Spalte mit einem Button anzeigbar ist. Mal sehen wie ich die nächsten Tage dazu komme. Kann jemand Hinweise geben wie das umgesetzt werden könnte?

2021-10-03 06:15 UTC, buchen requested changes
Hi @OnkelDok,

die Fehler in den Unit Tests kommen daher, dass es verschiedene Methoden gibt um eine Datei zu persistieren. Im aktuellen Master branch ist die Unterstützung für Protobuf schon gemergt. Die Protobuf Dateien werden in client.proto definiert und während dem Build generiert.

Ich tendiere dazu, dass die Einstellungen eher eine ```Map<String, Object>``` ist. Da sieht der Code nicht ganz so schön aus, aber das ist viel einfacher zu serialisieren (und vor allem viel einfacher kompatibel weiterzuentwickeln). Und dann könnte man einen generisches Objekt hinterlegen (und den Code in Classification#toProtobuf eventuell refactoren).

Vorschlag: ich baue ein solches generisches Objekt und comitte das in den master branch. Du machst ein rebase Deiner Änderungen und passt die limit price settings entsprechend an.


Zu dem UI: Ich denke die Konfiguration sollte in dem unteren Bereich ("InformationPanes") stattfinden. Den gibt es schon. Du musst in der View die Methode #addPanePages überschreiben. Und dann an die Tabelle mit den Attributen ein #addSelectionChangedListener Aufruf hängen, der die #setInformationPaneInput aufruft.

<img width="599" alt="Bildschirmfoto 2021-10-03 um 07 39 12" src="https://user-images.githubusercontent.com/587976/135742230-a1702af4-dd42-4b34-83aa-6541d95b4713.png">

2021-10-03 14:29 UTC, OnkelDok commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/AttributeColumn.java
> +                var joiner = new StringJoiner(" / "); //$NON-NLS-1$
Das hat sich eingeschlichen aus C#. Nun weiß ich Bescheid wieso das nicht verwendet werden soll. Danke für den Hinweis.

2021-10-03 14:41 UTC, OnkelDok commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/AttributeColumn.java
> +            SecurityPrice latestSecurityPrice = security.getSecurityPrice(LocalDate.now());
@buchen: 
Ich habe mal gesucht nach ".getSecurityPrice(LocalDate.now());" und 20 Treffer erhalten. Wenn die Operation (Abfrage des letzten Preises) recht teuer ist, aber häufig verwendet wird: Könnte man das Ergebnis der Abfrage nicht cachen und bei bestimmten Aktionen den Cache leeren (wenn neue Kursdaten abgerufen oder manuell eingepflegt wurden). Auf jeden Fall könnte das auch lokal im "LimitPriceLabelProvider" geschehen. Ich hatte nämlich zusätzlich darüber nachgedacht pauschal den Abstand von Preis zu Limit im Tooltip der Zelle anzuzeigen. Das würde ja dann immer angezeigt, egal ob die beiden neuen Einstellungen aktiv sind oder nicht. Mit lokalem cache im "LimitPriceLabelProvider" würde die Operation dann nur 1x aufgerufen werden aber an 3 Stellen (Berechnung Hintergrundfarbe, Berechnung Abstände für Tooltip, Berechnung Tooltip (optional)) verwendet werden.

2021-10-03 14:59 UTC, OnkelDok commented
> 
> Ich tendiere dazu, dass die Einstellungen eher eine `Map<String, Object>` ist. Da sieht der Code nicht ganz so schön aus, aber das ist viel einfacher zu serialisieren (und vor allem viel einfacher kompatibel weiterzuentwickeln). Und dann könnte man einen generisches Objekt hinterlegen (und den Code in Classification#toProtobuf eventuell refactoren).
> 
> Vorschlag: ich baue ein solches generisches Objekt und comitte das in den master branch. Du machst ein rebase Deiner Änderungen und passt die limit price settings entsprechend an.
>

@buchen Du meinst also alle (zukünftigen) Attributseinstellungen nicht direkt als jeweiliger Unterknoten von "AttributeType" sondern als extra "Liste" wobei jedes Element über die GUID dem Attribut zugeordnet ist? Wenn das bezüglich Kompatibilität und Serialisation sinnvoller ist, gerne.
 
>
> Zu dem UI: Ich denke die Konfiguration sollte in dem unteren Bereich ("InformationPanes") stattfinden. Den gibt es schon. Du musst in der View die Methode #addPanePages überschreiben. Und dann an die Tabelle mit den Attributen ein #addSelectionChangedListener Aufruf hängen, der die #setInformationPaneInput aufruft.
> 

Ah ja. Das Panel gibt es ja auch. Das schau ich mir bei der nächsten Gelegenheit an. Danke für den Hinweis. Den einzigen Nachteil den ich sehe beim Anklicken der Zeile ist, dass man als Benutzer nicht direkt sieht, welches Attribut Einstellungen hat und welches nicht. Aber man könnte die Attribute mit Einstellungen ja noch kenntlich machen in der Liste (kleines Icon?).

2021-10-03 15:18 UTC, buchen commented
> Du meinst also alle (zukünftigen) Attributseinstellungen nicht direkt als jeweiliger Unterknoten von "AttributeType" sondern als extra "Liste" wobei jedes Element über die GUID dem Attribut zugeordnet ist? Wenn das bezüglich Kompatibilität und Serialisation sinnvoller ist, gerne.

Ich habe gerade eben den Change gepusht. Du kannst jetzt mit ```getProperties().putBoolean("showRelativeDiff", true)``` Eigenschaften speichern.
Es ist also kein typisiertes Settings Objekt sondern eine Map. Natürlich macht es Sinn an einer Stelle die Keys zu definieren (analog wie das für ```UIConstants``` gemacht ist). Vielleicht ```AttributeTypeProperties.LimitPrice.SHOW_RELATIVE_DIFF```?!?)


> Aber man könnte die Attribute mit Einstellungen ja noch kenntlich machen in der Liste (kleines Icon?)

Das ist eine gute Idee.

2021-10-03 17:54 UTC, OnkelDok commented
> Ich habe gerade eben den Change gepusht.

Danke. Nun verstehe ich was du meinst. Was denkst du auf welche Art eine Farbe (Color) in der Map angelegt werden sollte?
Als integer (alle 4 Kanäle in die Bytes gebracht), oder auf andere Art? Wurden an anderer Stelle schonmal Farben in der EInstellungsdatei hinterlegt?

2021-10-03 21:59 UTC, chirlu commented
force-push

2021-10-29 21:03 UTC, buchen commented
@OnkelDok Okay, endlich bin ich dazu gekommen mir die Änderungen im Detail anzuschauen. Ich habe noch ein paar Anpassungen vorgenommen, aber jetzt ist das Feature im master branch. Vielen Dank! Und vielen Dank für Deine Geduld.

Kurz zu dem was ich geändert habe (schau Dir gerne den Code im Detail an):
* Ich habe jetzt "limit exceeded" und "limit undercut" umbenannt in "limit exceeded positively" and "limit exceeded negatively". Warum? Eine Farbe wird ja nur angezeigt, wenn das Limit überschritten ist. Die Farbe unterscheidet sich dann aber wenn das positiv ist (ist größer als das Limit) oder negativ ist (ist kleiner als das Limit). Ansonsten gibt es ja keine Hintergrundfarbe. Die alte Benennung impliziert das es eine Farbe gibt wenn das Limit nicht erreicht wurde. Gibt es aber nicht.
* Die default Werte dürfen nicht im LimitPriceSettings Objekt gespeichert werden, denn ansonsten hat die Änderung des themes keine Auswirkung mehr auf die Farben. "null" im settings bedeutet immer: nimm die Farbe aus dem Theme. Jetzt wird beim zurücksetzen der Farben "null" gespeichert. Und beim swap wird geprüft ob man wieder zurück zu den default Farben geswappt hat und dann der Wert auf "null" gesetzt
* Named und Annotated habe ich noch nicht geändert. Aber ich stimme Deinem Kommentar zu. Vermutlich müssen die einfach nebeneinander stehen. Es gibt Objekte die haben nur eine Notiz aber keinen Namen (wie eine Buchung) und es kann Objekte geben, die haben einen Namen, aber keine Notiz (wie ein Attribut). Bisher gab es letzteres einfach nicht.

2021-10-29 21:03 UTC, closed without merging